### PR TITLE
Add Fastify serve handler

### PR DESCRIPTION
**Pull request by djfarrelly**
## Description

Support the [Fastify](https://www.fastify.io/) framework with a new serve handler.

### TODO

* [x] Fix `req.query` typescript error
* [x] Add tests
* [x] Add documentation

### CODE REVIEW

**Comment by nnennajohn** [comment]
Hi, Is there any update on this? Considering Pipedream and came across Inngest and would love to try it. But we use fastify, so currently not possible. 

Are there any published work-around while this is pending?

Thank you.

**Comment by nnennajohn** [comment]
Hi @jpwilliams , awesome. Will try it out and let you know by EOD. Thanks so much.

**Comment by nnennajohn** [comment]
Hi @jpwilliams 

Took this for a test run. Success. Thanks so much 

Screenshot 2023-08-23 at 6 01 23 PM

**Comment by jpwilliams** [comment]
Awesome! Thanks for the update, @nnennajohn. We'll get this out and I'll update here so you can move back to the main branch. 🙂

**Comment by jpwilliams** [comment]
Thanks for testing this out, folks!

This has been released in [v2.6.0](https://github.com/inngest/inngest-js/releases/tag/inngest%402.6.0). 🙂

**Pull request merged**
